# Generated by Django 4.1 on 2022-08-29 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0006_song_artist_song_image_alter_album_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AlterField(
            model_name='album',
            name='uploaded_on',
            field=models.DateField(default=datetime.datetime(2022, 8, 29, 19, 26, 24, 101189, tzinfo=datetime.timezone.utc)),
        ),
    ]
