# Generated by Django 4.1 on 2022-08-29 20:37

import datetime
from django.db import migrations, models
import music_nation.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0009_remove_song_image_alter_album_uploaded_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=music_nation.models.user_directory_path_song),
        ),
        migrations.AlterField(
            model_name='album',
            name='uploaded_on',
            field=models.DateField(default=datetime.datetime(2022, 8, 29, 20, 37, 47, 769854, tzinfo=datetime.timezone.utc)),
        ),
    ]
